/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.SystemAdminWorkArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meetdoshi
 */

public class ManageEnterprisePanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem system;
    
    public ManageEnterprisePanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        populateComboBox();
        populateTable();
    }
    
    public void populateComboBox(){
        networkComboBox.removeAllItems();
        enterpriseTypeComboBox.removeAllItems();
        for(Network network : system.getNetworkDirectory()){
            networkComboBox.addItem(network);
        }
        for(Enterprise.EnterpriseType enterpriseType : Enterprise.EnterpriseType.values()){
            enterpriseTypeComboBox.addItem(enterpriseType);
        }
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) enterpriseTable.getModel();
        dtm.setRowCount(0);
        for(Network network : system.getNetworkDirectory()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterprisesDirectory()){
                Object[] row = new Object[3];
                row[0] = enterprise.getOrgnizationName();
                row[1] = network.getNetworkName();
                row[2] = enterprise.getEnterpriseType().getValue();
                
                dtm.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseTable = new javax.swing.JTable();
        networkLabel = new javax.swing.JLabel();
        enterpriseTypeLabel = new javax.swing.JLabel();
        enterpriseNameLabel = new javax.swing.JLabel();
        enterpriseNameTextField = new javax.swing.JTextField();
        networkComboBox = new javax.swing.JComboBox();
        enterpriseTypeComboBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleJLabel.setText("Manage Enterprise");
        add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 26, -1, -1));

        enterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Enterprise Type"
            }
        ));
        jScrollPane1.setViewportView(enterpriseTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 102, -1, 180));

        networkLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkLabel.setText("Network :");
        add(networkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 355, 115, -1));

        enterpriseTypeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseTypeLabel.setText("Enterprise Type :");
        add(enterpriseTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 424, -1, -1));

        enterpriseNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseNameLabel.setText("Enterprise Name :");
        add(enterpriseNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 505, -1, -1));

        enterpriseNameTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(enterpriseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 502, 164, -1));

        networkComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 352, 164, -1));

        enterpriseTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 421, 164, -1));

        submitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 591, -1, 40));

        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BluePlain-4.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, 790, 820));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Network network = (Network) networkComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType)enterpriseTypeComboBox.getSelectedItem();
        if (network == null || type == null){
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        String name = enterpriseNameTextField.getText();
        Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
        
        populateTable();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterpriseNameLabel;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JTable enterpriseTable;
    private javax.swing.JComboBox enterpriseTypeComboBox;
    private javax.swing.JLabel enterpriseTypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkComboBox;
    private javax.swing.JLabel networkLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
